Repository DesignSystemsOSS/eccentrictouch, pull requests merged in 2021-06, with the labels that each got.

#256 Added border width classes(#247)
  src/lib/eccentric.css
  src/lib/eccentric.css.map
  src/lib/eccentric.scss
Labels: LGMSOC21, 🟧 Level3

#260 Added border-color classes(#242)
  src/lib/eccentric.css
  src/lib/eccentric.css.map
  src/lib/eccentric.scss
Labels: LGMSOC21, 🟧 Level3

#262 Refactored Css
  src/lib/eccentric.css
  src/lib/eccentric.css.map
  src/lib/eccentric.scss
  src/tests/border.html
Labels: LGMSOC21, 🟥 Level4

#263 Adding Border Radius (#240)
  src/lib/eccentric.css
  src/lib/eccentric.css.map
  src/lib/eccentric.scss
  src/tests/border.html
Labels: LGMSOC21, 🟧 Level3

#279 hover and css effects added to buttons(#226)
  src/lib/eccentric.css
  src/lib/eccentric.css.map
  src/lib/eccentric.scss
Labels: LGMSOC21, code: css, enhancement, 🟨 Level2
